### ISSUE TITLE
Call balanceOfDaiAvailableToMint to avoid rewriting the function

### ISSUE THREAD

**Issue by therealmonoloco** [mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC#10]
https://github.com/mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC/blob/1c0cb03f2313c9becd64ff6b6c25ab39a9d38370/contracts/libraries/MakerDaiDelegateLib.sol#L322-L332

You added a new `balanceOfDaiAvailableToMint` function based on `isDaiAvailableToMint`. The latter can now simply return `balanceOfDaiAvailableToMint >= MIN_MINTABLE`.

**Comment by mil0xeth** [comment]
Good catch. Fixed.
