### ISSUE TITLE
Extract min profit to its own variable

### ISSUE THREAD

**Issue by therealmonoloco** [mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC#3]
https://github.com/mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC/blob/1c0cb03f2313c9becd64ff6b6c25ab39a9d38370/contracts/Strategy.sol#L219-L220

It could make sense to extract the 1e17 magic minimum profit to its own variable.

**Comment by mil0xeth** [comment]
Added a variable minSingleTrade that represents Minimum Profit to be taken and Minimum Single Trade size. 
Variable can be updated with setMinMaxSingleTrade(uint256 minSingleTrade, uint256 maxSingleTrade)
