### ISSUE TITLE
Make it clear that this is DAI/USDC

### ISSUE THREAD

**Issue by therealmonoloco** [mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC#5]
https://github.com/mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC/blob/1c0cb03f2313c9becd64ff6b6c25ab39a9d38370/contracts/Strategy.sol#L428-L431

I would rewrite this so it is a bit more clear that tuple contains (Dai amount, USDC amount). I would also simplify `(wantUnderlyingBalance.mul(WAD).add(otherTokenUnderlyingBalance.mul(WAD).mul(WAD).div(1e6))).div(yieldBearing.totalSupply());` to (double check!) `(wantUnderlyingBalance.add(otherTokenUnderlyingBalance.mul(1e12)).mul(WAD).div(yieldBearing.totalSupply();` to remove some redundant operations and save some gas.

**Comment by mil0xeth** [comment]
Fixed. Nice way to save gas, thanks.
