### ISSUE TITLE
Incorrect ethToWant

### ISSUE THREAD

**Issue by therealmonoloco** [mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC#7]
https://github.com/mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC/blob/1c0cb03f2313c9becd64ff6b6c25ab39a9d38370/contracts/Strategy.sol#L344

This function is expected to return the amount in `want` of `_amtInEth`, so current implementation is incorrect. Only usage I can think of is calculating call cost, so probably safe to ignore but would at least add a comment stating it is being purposefully ignored. Another reviewer might have more data as to whether an external party such as a frontend is relying on this function.

**Comment by mil0xeth** [comment]
Fixed. Discussing this with dudesahn lead to a small rewrite of that function and harvestTrigger.
